title: "Matthew J. Monnot, PhD"
description: "Industrial-Organizational Psychologist | Organization Development Consultant | People and Workplace Researcher | Thought Leader | Athlete"
theme: minima

url: "https://mjmonnot.github.io"
baseurl: ""

author:
  name: "Matthew J. Monnot, PhD"
  email: ""

minima:
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv.html
    - title: "Publications"
      url: /publications.html
    - title: "Themes"
      url: /themes/leadership-and-wellbeing.html"
