title: "Matthew J. Monnot, PhD"
description: "I-O Psychologist · People Scientist · OD Consultant"
theme: minima

url: "https://mjmonnot.github.io"
baseurl: ""

# author:
#   name: "Matthew J. Monnot, PhD"
#   email: ""

minima:
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv.html
    - title: "Publications"
      url: /publications.html
    - title: "Themes"
      url: /themes/leadership-and-wellbeing.html
    - title: "Media"
      url: /press.html



social_links:
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/monnot"
  - platform: x
    user_url: "https://x.com/Matt_Monnot"
  - platform: google-scholar
    user_url: "https://scholar.google.com/citations?user=BhmHT_UAAAAJ&hl=en"
