title: "Matthew J. Monnot, PhD"
description: "Industrial-Organizational Psychologist | Organization Development Consultant | People and Workplace Researcher | Thought Leader | Athlete"
theme: minima

url: "https://mjmonnot.github.io"
baseurl: ""

author:
  name: "Matthew J. Monnot, PhD"
  email: ""

minima:
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv.html
    - title: "Publications"
      url: /publications.html
    - title: "Themes"
      url: /themes/leadership-and-wellbeing.html"

# Social links (these will show in the footer by default)
social_links:
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/monnot"
  - platform: twitter
    user_url: "https://x.com/Matt_Monnot"
  - platform: google-scholar
    user_url: "https://scholar.google.com/citations?user=BhmHT_UAAAAJ&hl=en"
